"""Write or verify THIRD-PARTY.md, the inventory of what ships inside a build.

    python scripts/generate_third_party.py --write
    python scripts/generate_third_party.py --check

The list is the runtime dependency table from pyproject.toml, so it is the same on every
machine. Licences are read from the installed distribution when there is one, which is why
--check runs on a single CI runner: a dependency restricted to another platform is not
installed here and its licence cannot be read. Such entries say so instead of guessing.

CI runs --check so that adding or removing a dependency without regenerating this file
fails the build.
"""

import argparse
import re
import sys
import tomllib
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD-PARTY.md"
SPECIFIER = re.compile(r"[<>=!~]")

HEADER = """# Third-party components

Audio Recorder is distributed with the Python packages below, together with the
dependencies those packages bring in themselves. Each remains under its own licence, held
by its own authors.

This file is generated by `scripts/generate_third_party.py`, do not edit it by hand.

"""

FOOTER = """
A build also embeds the CPython runtime (Python Software Foundation Licence) and the Qt
libraries PyQt6 binds to (LGPL v3), both collected by PyInstaller.

Run `pip download` or read each project's page for the full licence text and for the
dependencies these packages pull in.
"""

NOT_INSTALLED = "restricted to another platform, see the package"


def declared_dependencies():
    with open(ROOT / "pyproject.toml", "rb") as f:
        data = tomllib.load(f)

    dependencies = []
    for entry in data["project"]["dependencies"]:
        requirement, _, marker = entry.partition(";")
        requirement = requirement.strip()
        match = SPECIFIER.search(requirement)
        name = requirement[:match.start()].strip() if match else requirement
        specifier = requirement[match.start():].strip() if match else ""
        dependencies.append((name, specifier, marker.strip()))
    return sorted(dependencies)


def licence_of(name):
    try:
        dist = metadata.distribution(name)
    except metadata.PackageNotFoundError:
        return NOT_INSTALLED

    expression = dist.metadata.get("License-Expression")
    if expression:
        return expression
    for classifier in dist.metadata.get_all("Classifier") or []:
        if classifier.startswith("License :: "):
            return classifier.rsplit("::", 1)[-1].strip()
    declared = dist.metadata.get("License")
    if declared and len(declared) < 60 and "\n" not in declared:
        return declared.strip()
    return "see the package"


def render():
    rows = []
    for name, specifier, marker in declared_dependencies():
        requirement = specifier or "any"
        platform_note = f" ({marker})" if marker else ""
        rows.append(
            f"| [{name}](https://pypi.org/project/{name}/) | `{requirement}`{platform_note} "
            f"| {licence_of(name)} |")

    table = ("| Package | Required | Licence |\n| --- | --- | --- |\n"
             + "\n".join(rows) + "\n")
    return HEADER + table + FOOTER


def main():
    parser = argparse.ArgumentParser(description="Generate or verify THIRD-PARTY.md.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write the file")
    group.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args()

    generated = render()
    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT.name}")
        return 0

    if not OUTPUT.exists():
        print(f"{OUTPUT.name} is missing. Run: python scripts/generate_third_party.py --write",
              file=sys.stderr)
        return 1
    if OUTPUT.read_text(encoding="utf-8") != generated:
        print(f"{OUTPUT.name} is out of date. "
              "Run: python scripts/generate_third_party.py --write", file=sys.stderr)
        return 1
    print(f"{OUTPUT.name} is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
